# Site settings
title: Sofie Verrewaere
header-img: img/home-bg.jpg
email: sofieverrewaere@gmail.com
description: "Blog of Tom Van de Wiele. Read about my projects."
baseurl: ""
url: "https://sofieverrewaere.github.io"
facebook_username: sofie.ver.1
github_username: SofieVerrewaere
linkedin_username: sofieverrewaere

# Build settings
markdown: kramdown
highlighter: rouge
future: true
permalink: /:title/
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

analytics :
  provider : google
  google : 
    tracking_id : 'UA-89904117-1'
  getclicky :
    site_id : 
